insert into santinho_partido(id, sigla, nome, numero) values(1, 'PMDB', 'PARTIDO DO MOVIMENTO DEMOCRÁTICO BRASILEIRO', 15);
insert into santinho_partido(id, sigla, nome, numero) values(2, 'PTB', 'PARTIDO TRABALHISTA BRASILEIRO', 14);
insert into santinho_partido(id, sigla, nome, numero) values(3, 'PDT', 'PARTIDO DEMOCRÁTICO TRABALHISTA', 12);
insert into santinho_partido(id, sigla, nome, numero) values(4, 'PT', 'PARTIDO DOS TRABALHADORES', 13);
insert into santinho_partido(id, sigla, nome, numero) values(5, 'DEM', 'DEMOCRATAS', 25);
insert into santinho_partido(id, sigla, nome, numero) values(6, 'PC do B', 'PARTIDO COMUNISTA DO BRASIL', 65);
insert into santinho_partido(id, sigla, nome, numero) values(7, 'PSB', 'PARTIDO SOCIALISTA BRASILEIRO', 40);
insert into santinho_partido(id, sigla, nome, numero) values(8, 'PSDB', 'PARTIDO DA SOCIAL DEMOCRACIA BRASILEIRA', 45);
insert into santinho_partido(id, sigla, nome, numero) values(9, 'PTC', 'PARTIDO TRABALHISTA CRISTÃO', 36);
insert into santinho_partido(id, sigla, nome, numero) values(10, 'PSC', 'PARTIDO SOCIAL CRISTÃO', 20);
insert into santinho_partido(id, sigla, nome, numero) values(11, 'PMN', 'PARTIDO DA MOBILIZAÇÃO NACIONAL', 33);
insert into santinho_partido(id, sigla, nome, numero) values(12, 'PRP', 'PARTIDO REPUBLICANO PROGRESSISTA', 44);
insert into santinho_partido(id, sigla, nome, numero) values(13, 'PPS', 'PARTIDO POPULAR SOCIALISTA', 23);
insert into santinho_partido(id, sigla, nome, numero) values(14, 'PV', 'PARTIDO VERDE', 43);
insert into santinho_partido(id, sigla, nome, numero) values(15, 'PT do B', 'PARTIDO TRABALHISTA DO BRASIL', 70);
insert into santinho_partido(id, sigla, nome, numero) values(16, 'PP', 'PARTIDO PROGRESSISTA', 11);
insert into santinho_partido(id, sigla, nome, numero) values(17, 'PSTU', 'PARTIDO SOCIALISTA DOS TRABALHADORES UNIFICADO', 16);
insert into santinho_partido(id, sigla, nome, numero) values(18, 'PCB', 'PARTIDO COMUNISTA BRASILEIRO', 21);
insert into santinho_partido(id, sigla, nome, numero) values(19, 'PRTB', 'PARTIDO RENOVADOR TRABALHISTA BRASILEIRO', 28);
insert into santinho_partido(id, sigla, nome, numero) values(20, 'PHS', 'PARTIDO HUMANISTA DA SOLIDARIEDADE', 31);
insert into santinho_partido(id, sigla, nome, numero) values(21, 'PSDC', 'PARTIDO SOCIAL DEMOCRATA CRISTÃO', 27);
insert into santinho_partido(id, sigla, nome, numero) values(22, 'PCO', 'PARTIDO DA CAUSA OPERÁRIA', 29);
insert into santinho_partido(id, sigla, nome, numero) values(23, 'PTN', 'PARTIDO TRABALHISTA NACIONAL', 19);
insert into santinho_partido(id, sigla, nome, numero) values(24, 'PSL', 'PARTIDO SOCIAL LIBERAL', 17);
insert into santinho_partido(id, sigla, nome, numero) values(25, 'PRB', 'PARTIDO REPUBLICANO BRASILEIRO', 10);
insert into santinho_partido(id, sigla, nome, numero) values(26, 'PSOL', 'PARTIDO SOCIALISMO E LIBERDADE', 50);
insert into santinho_partido(id, sigla, nome, numero) values(27, 'PR', 'PARTIDO DA REPÚBLICA', 22);
insert into santinho_partido(id, sigla, nome, numero) values(28, 'PSD', 'PARTIDO SOCIAL DEMOCRÁTICO', 55);
insert into santinho_partido(id, sigla, nome, numero) values(29, 'PPL', 'PARTIDO PÁTRIA LIVRE', 54);
insert into santinho_partido(id, sigla, nome, numero) values(30, 'PEN', 'PARTIDO ECOLÓGICO NACIONAL', 51);
insert into santinho_partido(id, sigla, nome, numero) values(31, 'PROS', 'PARTIDO REPUBLICANO DA ORDEM SOCIAL', 90);
insert into santinho_partido(id, sigla, nome, numero) values(32, 'SD', 'SOLIDARIEDADE', 77);